Repository sous-chefs/java, pull requests merged in 2019-02, with the labels that each got.

#497 Added AdoptOpenJDK as a install flavor and update the certificate resource to use Ruby for openssl
  .kitchen.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  recipes/adoptopenjdk.rb
  recipes/set_attributes_from_version.rb
  resources/adoptopenjdk_install.rb
  resources/certificate.rb
  spec/adoptopenjdk_spec.rb
  spec/default_spec.rb
  templates/adoptopenjdk.jinfo.erb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk-10-hotspot.rb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk-10-openj9.rb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk-11-hotspot.rb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk-11-openj9-large-heap.rb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk-11-openj9.rb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk-8-openj9.rb
  test/fixtures/cookbooks/test/recipes/remove-adoptopenjdk-11-openj9.rb
  test/integration/adoptopenjdk/attributes/adoptopenjdk-10-hotspot.yml
  test/integration/adoptopenjdk/attributes/adoptopenjdk-10-openj9.yml
  test/integration/adoptopenjdk/attributes/adoptopenjdk-11-hotspot.yml
  test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9-large-heap.yml
  test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9.yml
  test/integration/adoptopenjdk/attributes/adoptopenjdk-8-openj9.yml
  test/integration/adoptopenjdk/controls/verify_adoptopenjdk.rb
  test/integration/adoptopenjdk/inspec.yml
  test/integration/remove-adoptopenjdk/controls/verify_adoptopenjdk-removal.rb
  test/integration/remove-adoptopenjdk/inspec.yml
Labels: Awaiting Feedback, Type: Feature Request

#428 default to version 8
  attributes/default.rb
  spec/openjdk_spec.rb
  spec/oracle_jce_spec.rb
  spec/set_attributes_from_version_spec.rb
Labels: Impact: Breaking Changes, Status: Pending Contributor

#452 java_home cannot be nil for JAVA 8 installs
  recipes/windows.rb
Labels: Awaiting Feedback, Status: Pending Contributor
