Repository sous-chefs/java, pull requests merged in 2022-02, with the labels that each got.

#670 Add Cookstyle back into the required checks
  .github/workflows/test-kitchen.yml
Labels: Release: Patch, Skip: Announcements

#671 Automated PR: Standardising Files
  .overcommit.yml
  CHANGELOG.md
Labels: Release: Patch, Skip: Announcements

#668 Resource partials
  CHANGELOG.md
  metadata.rb
  resources/adoptopenjdk_install.rb
  resources/adoptopenjdk_linux_install.rb
  resources/adoptopenjdk_macos_install.rb
  resources/alternatives.rb
  resources/certificate.rb
  resources/corretto_install.rb
  resources/jce.rb
  resources/openjdk_install.rb
  resources/openjdk_pkg_install.rb
  resources/openjdk_source_install.rb
  resources/partial/_common.rb
  resources/partial/_java_home.rb
  resources/partial/_linux.rb
  resources/partial/_macos.rb
Labels: Release: Major

#672 Elevate permissions for GitHub reusable workflow
  .github/workflows/test-kitchen.yml
  CHANGELOG.md
Labels: Release: Patch
