Repository sous-chefs/java, pull requests merged in 2023-09, with the labels that each got.

#699 Use standard dokken file and remove EOL Debian 9
  .github/workflows/test-kitchen.yml
Labels: Release: Minor

#676 AdoptOpenJDK --> Termurin/Semeru
  CHANGELOG.md
  kitchen.yml
  libraries/adopt_openjdk_helpers.rb
  libraries/openjdk_helpers.rb
  resources/adoptopenjdk_linux_install.rb
  resources/openjdk_source_install.rb
  spec/libraries/adopt_openjdk_helpers_spec.rb
  spec/libraries/adopt_openjdk_macos_helpers_spec.rb
  spec/libraries/openjdk_helpers_spec.rb
  spec/libraries/semeru_helpers_spec.rb
  spec/spec_helper.rb
  test/fixtures/cookbooks/test/recipes/adoptopenjdk.rb
  test/fixtures/cookbooks/test/recipes/openjdk.rb
Labels: In Progress, Release: Major

#702 fix: typo, 'opendjdk' should be 'openjdk'
  CHANGELOG.md
  resources/openjdk_source_install.rb
Labels: Release: Patch
